version: "3.9"
name: "streaming-app"

services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming-app
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - streaming-app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - streaming-app

  media-server:
    container_name: media-server
    restart: unless-stopped
    build: ./media-server
    ports:
      - "1935:1935"
      - "8000:8000"
    networks:
      - streaming-app

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "5117:8080"
    networks:
      - streaming-app

networks:
  streaming-app:
    driver: bridge
    name: streaming-app
