name: "streaming-app"

services:
  nginx-rtmp:
    container_name: nginx-rtmp
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./media-server/rtmp/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - streaming-app

  stream-gateway:
    container_name: stream-gateway
    build:
      context: ./media-server/gateway
      dockerfile: Dockerfile
    environment:
      - STREAM_API_BASE_URL=http://backend:8080/api
      - STREAM_API_KEY=AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY
    volumes:
      - ./media-server/rtmp/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - streaming-app

  database:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streaming-app
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - streaming-app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - streaming-app

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

    ports:
      - "5117:8080"
    networks:
      - streaming-app

networks:
  streaming-app:
    driver: bridge
    name: streaming-app
