version: "3.9"

name: "nginx-rtmp"

services:
  nginx-rtmp:
    container_name: nginx-rtmp
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - streaming-app

  stream-gateway:
    container_name: stream-gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - STREAM_API_URL=http://backend:8080/api
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - streaming-app

networks:
  streaming-app:
    driver: bridge
    external: true
